### ISSUE TITLE
Chore: Update `homepage` from "http://lisperator.net/uglifyjs"

### ISSUE THREAD

**Issue by nelsonic** [LuchoTurtle/tweakpane-plugin-file-import#4]
Consider updating the `homepage` link on NPM:
https://www.npmjs.com/package/tweakpane-plugin-file-import
<img width="1365" alt="lucho-tweakpane-homepage-link" src="https://github.com/LuchoTurtle/tweakpane-plugin-file-import/assets/194400/c725f8c1-60d6-49eb-a4e0-ccd84425e0c3">

This is the line:

https://github.com/LuchoTurtle/tweakpane-plugin-file-import/blob/6345e132fa8079b30afbf2a1843799f3610e7db9/package.json#L5

Should be: `"https://github.com/LuchoTurtle/tweakpane-plugin-file-import"` 🔗 
Unless you have a web page for the package. 💭

**Comment by LuchoTurtle** [comment]
Fixed on https://github.com/LuchoTurtle/tweakpane-plugin-file-import/commit/d5d6be09370885f8c0303f05b3aa127650d3e861.
Thanks 👌
