### ISSUE TITLE
Button instead of input field?

### ISSUE THREAD

**Issue by kingsushi001** [LuchoTurtle/tweakpane-plugin-file-import#5]
Hi

I am pretty new to JS, trying to learn as I go.

I have tried your Tweakpane plugin, but for some reason I get a text input field instead of a button.

This is my code:
```
const createPane = () => {
    const pane = new Tweakpane.Pane();
    pane.registerPlugin(FileImportPlugin);
    let folder;

    folder = pane.addFolder({ title: 'Settings'});
    
    folder.addInput(params, 'File', {
		view: 'file-input',
		lineCount: 3,
		filetypes: ['.mp3'],
	})
        .on('change', (ev) => {
            AudioPath(params.File);
	});
}
```
And this is what I get:
![image](https://github.com/LuchoTurtle/tweakpane-plugin-file-import/assets/12822180/6c0ad2a8-3861-4441-901d-e79c3da30811)

What do I need to do to get this?:
![image](https://github.com/LuchoTurtle/tweakpane-plugin-file-import/assets/12822180/45773599-db5f-4fb7-833e-b3e82812812d)

Any help will be greatly appreciated.

**Comment by LuchoTurtle** [comment]
Hey there! @kingsushi001 
Thanks for opening an issue!

The most likely reason for this is because your `File` field in the `params` object is not an empty string.

```js
const params = {
	file: '',
};

pane
	.addInput(params, 'file', {
		view: 'file-input',
		lineCount: 3,
		filetypes: ['.png', '.jpg'],
	})
	.on('change', (ev) => {
		console.log(ev.value);
	});
```

It should work if you initialize it like so 😄

**Comment by kingsushi001** [comment]
Thank you for the response. 

I forgot to post the `params` as well. I indeed do have `File` set to an empty string.
```
const params = {
    File: '',
    Preset: '1',
}
```

**Comment by LuchoTurtle** [comment]
Hmm, interesting...
Try to switch your line from

```js
pane.registerPlugin(FileImportPlugin);
```

to 

```js
pane.registerPlugin(TweakpaneFileImportPlugin);
```

If this solves the issue, the README is outdated and I ought to update it 😅

**Comment by kingsushi001** [comment]
lol, this seems to add the button and I am able to load an mp3, but everything breaks after that. Even when selecting the same mp3

**Comment by kingsushi001** [comment]
It's all good. lol, it's probably just my lack of JS knowledge that is breaking everything.

I unfortunately don't have a link, because like I have mentioned before, it's an Electron app.
Can I zip the VS Code project folder and link you to that? Preferably privately.

**Comment by LuchoTurtle** [comment]
Sure thing! You can link me at lucho_garfield@hotmail.com.
I've never worked with Electron but I'm curious to see if the problem is related to the package or not 😄

**Comment by kingsushi001** [comment]
I have no idea how different Electron is as apposed to a normal browser, as this is the first JS app I've tried creating.

Also, thank you very much. I have sent you the link.

**Comment by LuchoTurtle** [comment]
I haven't received anything, perhaps you've typed the e-mail wrong 💭

**Comment by kingsushi001** [comment]
Hmmm, I copied and pasted the address 
![image](https://github.com/LuchoTurtle/tweakpane-plugin-file-import/assets/12822180/70366102-c8c0-4a16-8548-0f368de696be)

**Comment by LuchoTurtle** [comment]
Got it! I'll take a look when I have the time :)

**Comment by kingsushi001** [comment]
Thank you so much for your help and explanation.

Lol, it's like I said, lack of JS knowledge. But I am learning witch each mistake I make.

**Comment by LuchoTurtle** [comment]
For sure! The only path to learning is by making mistakes!
Thanks for opening the issue, have fun learning JS! 👏
