### ISSUE TITLE
iOS: input file click not triggered

### ISSUE THREAD

**Issue by Matoseb** [LuchoTurtle/tweakpane-plugin-file-import#53]
Hello, it seems that the input.click() is not triggered with a `mousedown` or `touchstart` event. It should be attached on the `click` event instead. Found this bug on iOS 16

**Comment by LuchoTurtle** [comment]
Hey, thanks for opening an issue.

Care to expand on what went wrong? Do you mean that the following line is not being executed on iOS 16? 

https://github.com/LuchoTurtle/tweakpane-plugin-file-import/blob/548e1144ad5b69684b4d855e34b53e3d9fd10652/src/controller/controller.ts#L102

Are you using which browser?

**Comment by Matoseb** [comment]
> Care to expand on what went wrong? Do you mean that the following line is not being executed on iOS 16?

It's indeed this line. I would say this action is ignored because it was not triggered from a `click` but with touchstart/mousedown from used in the tweakpane PointerHandler.

> Are you using which browser?

Safari

**Comment by LuchoTurtle** [comment]
@Matoseb thanks for opening. The issues has been fixed in `v1.0.2`. 👌
